version: "3"
services:
  node-app:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=7000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=manish
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis


volumes:
  mongo-db:
