version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "7001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    # ports:
    #   - "7000:7000" 
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=7000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=manish
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db
    # ports:
    #   - "27017:27017"
  redis:
    image: redis
    # ports:
    #   - "6379:6379"


volumes:
  mongo-db:
