version: "3"
services:
  prod-node:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=7000
    # env_file:
    #   - ./.env
